spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    dakar:
      url: jdbc:mysql://localhost:3306/ventes_dakar?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: nogaye
      password: sow2004
      driver-class-name: com.mysql.cj.jdbc.Driver

    thies:
      url: jdbc:mysql://localhost:3306/ventes_thies?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: nogaye
      password: sow2004
      driver-class-name: com.mysql.cj.jdbc.Driver

    stl:
      url: jdbc:mysql://localhost:3306/ventes_stlouis?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: nogaye
      password: sow2004
      driver-class-name: com.mysql.cj.jdbc.Driver

sync:
  interval-ms: 60000
